name: mlf
channels:
  - defaults
  - conda-forge
  - pytorch
  - pip
dependencies:
  - python=3.10.0
  - mkl < 2022
  - pandas=1.4.0
  - numpy
  - tqdm
  - pytorch
  - jupyterlab
  - matplotlib
  - ipywidgets
  - cvxopt
  - kneed
  - scikit-learn
