python run_forecasting.py --portfolio_method linear-ridge --strategy_type m --num_assets_to_select 2 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type m --num_assets_to_select 3 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type m --num_assets_to_select 4 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lo --num_assets_to_select 2 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lo --num_assets_to_select 3 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lo --num_assets_to_select 4 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lns --num_assets_to_select 2 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lns --num_assets_to_select 3 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lns --num_assets_to_select 4 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type los --num_assets_to_select 2 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type los --num_assets_to_select 3 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type los --num_assets_to_select 4 --cv_split_type tscv --cv_search_type random --random_regime False
python run_forecasting.py --portfolio_method linear-ridge --strategy_type m --num_assets_to_select 2 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type m --num_assets_to_select 3 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type m --num_assets_to_select 4 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lo --num_assets_to_select 2 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lo --num_assets_to_select 3 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lo --num_assets_to_select 4 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lns --num_assets_to_select 2 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lns --num_assets_to_select 3 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type lns --num_assets_to_select 4 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type los --num_assets_to_select 2 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type los --num_assets_to_select 3 --cv_split_type tscv --cv_search_type random --random_regime True
python run_forecasting.py --portfolio_method linear-ridge --strategy_type los --num_assets_to_select 4 --cv_split_type tscv --cv_search_type random --random_regime True